name: Pre-Commit Checks

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - develop

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files --show-diff-on-failure
      
      - name: Annotate failures
        if: failure()
        run: |
          echo "::error::Pre-commit hooks failed. Run 'pre-commit run --all-files' locally to fix issues."
